# workflow 이름설정
name: sobunsobun CI/CD 

# master branch에 push 될 때만 실행
on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-versions: [16.x]
          
    steps:
      # 저장소 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v2
      # 의존성 설치
      - name: Install Dependencies
        run: yarn install
      # env 설정
      - name: Setting .env
        run : |
          echo "REACT_APP_KAKAO_LOCAL_KEY=${{ secrets.REACT_APP_KAKAO_LOCAL_KEY }}" >> .env
          echo "REACT_APP_KAKAO_MAP_KEY=${{ secrets.REACT_APP_KAKAO_MAP_KEY }}" >> .env
          echo "SASS_PATH=${{ secrets.SASS_PATH }}" >> .env
          cat .env
      # 프로젝트 빌드
      - name: Project Build
        run: yarn build
      # AWS Configure 설정
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      # S3에 업로드
      - name: S3 Deploy
        run: |
          aws s3 cp --recursive --region ap-northeast-2 build s3://sobunsobun
      
 
        
       
    
  
